command: ["npm", "run", "start", "--workspace=backend"]

env:
  - name: ENCRYPTION_KEY
    valueFrom: encryption-key-secret
  - name: DB_URL
    valueFrom: db-url-secret
  - name: WAREHOUSE_ID_2XS
    valueFrom: warehouse-2xs
  - name: WAREHOUSE_ID_XS
    valueFrom: warehouse-2xs
  - name: WAREHOUSE_ID_S
    valueFrom: warehouse-2xs
